### ISSUE TITLE
'ele_hlts' --> 'ele_hlts_2017' (in whole file)

### ISSUE THREAD

**Issue by vinzenzstampf** [rmanzoni/HNL#11]
https://github.com/rmanzoni/HNL/blob/6d0832fe0ec1d9e313d512585955534595ab65a3/skim/skim_by_hlt_singleele_2017_cfg.py#L1

**Comment by vinzenzstampf** [comment]
and probably also for other occurances

**Comment by rmanzoni** [comment]
fixed
https://github.com/rmanzoni/HNL/commit/9ed4fc15a3b08ff55f845cea79e03b78348ec45a
