### ISSUE TITLE
missing reco vertex info from gen ntuple

### ISSUE THREAD

**Issue by vinzenzstampf** [rmanzoni/HNL#4]
[dxy_diff_chifit.pdf](https://github.com/rmanzoni/HNL/files/2081279/dxy_diff_chifit.pdf)

**Comment by dehuazhu** [comment]
here I would investigate whether the cause is from the vtx fit or from the reco particles. 
Maybe do hnl_2d_disp - l1_matched_muon_dxy ?

**Comment by rmanzoni** [comment]
ok, fixed, just need to push now
![schermata 2018-06-15 alle 18 44 06](https://user-images.githubusercontent.com/5039016/41479768-861ee5bc-70cc-11e8-95f8-813126f291c1.png)
![schermata 2018-06-15 alle 18 46 53](https://user-images.githubusercontent.com/5039016/41479769-863ad560-70cc-11e8-9d68-611f65f8fead.png)
