### ISSUE TITLE
PR to CMSSW on miniAOD content

### ISSUE THREAD

**Issue by rmanzoni** [rmanzoni/HNL#6]
Just for bookkeeping.
These should be the files to touch to add DSA muons to miniAOD.
Especially the last one.

https://github.com/cms-sw/cmssw/blob/master/Configuration/EventContent/python/EventContent_cff.py#L825
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/python/slimming/slimming_cff.py
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/PatAlgos/python/slimming/MicroEventContent_cff.py

@dehuazhu @vinzenzstampf

**Comment by vinzenz** [comment]
I guess highlighting me was probably a mistake, just in case you wanted someone else @rmanzoni

**Comment by rmanzoni** [comment]
ooops, right, my mistake.
Thanks for the heads-up

**Comment by rmanzoni** [comment]
done, in 10_2
https://github.com/cms-sw/cmssw/pull/23591
