### ISSUE TITLE
treat dgmuons

### ISSUE THREAD

**Issue by dehuazhu** [rmanzoni/HNL#9]
Syptom:
About 28% of the total events are events with displacedGlobalMuons selected as bestmatch candidate. This biases the efficiency plots, which only considers slimmedMuons and displacedStandAloneMuons. We need to find a way to treat them.

Proposal:
Remove displacedGlobalMuon from the Analysis

**Comment by rmanzoni** [comment]
interesting... It's funny that we did not found a good reason to include DGM before.
For the time being, removing them from the possible objects to match is absolutely reasonable.

**Comment by dehuazhu** [comment]
solved by commit 
[https://github.com/dehuazhu/HNL/commit/441aa65ecbcf15480143af52363c95f934cbc76e](url)
